import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddGameQuestions1751007349307 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE "game_questions"
                             (
                                 "created_at"  TIMESTAMP WITH TIME ZONE                 NOT NULL DEFAULT now(),
                                 "updated_at"  TIMESTAMP WITH TIME ZONE                 NOT NULL DEFAULT now(),
                                 "deleted_at"  TIMESTAMP WITH TIME ZONE,
                                 "id"          integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                 "game_id"     uuid                                     NOT NULL,
                                 "question_id" uuid                                     NOT NULL,
                                 CONSTRAINT "PK_8655fa1f9639162ee24c3a5582a" PRIMARY KEY ("id")
                             )`);

    await queryRunner.query(`ALTER TABLE "game_questions"
        ADD CONSTRAINT "FK_4c5351759926b365b1572dbdd1e" FOREIGN KEY ("game_id") REFERENCES "games" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "game_questions"
        ADD CONSTRAINT "FK_8b122e0afbb8b1a90a9b8c8ab56" FOREIGN KEY ("question_id") REFERENCES "questions" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "game_questions"
        DROP CONSTRAINT "FK_8b122e0afbb8b1a90a9b8c8ab56"`);
    await queryRunner.query(`ALTER TABLE "game_questions"
        DROP CONSTRAINT "FK_4c5351759926b365b1572dbdd1e"`);

    await queryRunner.query(`DROP TABLE "game_questions"`);
  }
}
